### ISSUE TITLE
java.io.FileNotFoundException while loading bitcoin.conf with Ubuntu 20.04

### ISSUE THREAD

**Issue by liorko87** [Polve/bitcoin-rpc-client#115]
I'm using the latest version of bitcoin RPC client.

When i'm trying to run my java application, I'm receiving this exception:
```
java.io.FileNotFoundException: /home/liork/AppData/Roaming/Bitcoin/bitcoin.conf (No such file or directory)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:195)
at java.io.FileInputStream.<init>(FileInputStream.java:138)
at wf.bitcoin.javabitcoindrpcclient.BitcoinJSONRPCClient.<clinit>(BitcoinJSONRPCClient.java:130)
```
`AppData/Roaming` exists only on Windows workstations and does not exists on UNIX workstations

**Comment by Polve** [comment]
Fixed in 1.2.2
